[package]
name = "cargo-gh-release"
version = "0.1.1"
edition = "2021"

[[bin]]
name = "cgh"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.93"
data-encoding = "2.6.0"
env_logger = "0.11.5"
flate2 = "1.0.35"
log = "0.4.22"
sha2 = "0.10.8"
tar = "0.4.43"
